### ISSUE TITLE
Шаблонизация тестового задания

### ISSUE THREAD

**Issue by tarampampam** [avtocod/python-developer-test-task#2]
Необходимо реализовать возможность использовать [данный репозиторий как шаблон](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) для "быстрого старта" выполнения задания.

Необходим функционал:

- [ ] Развернутого "скелетона" того фреймворка и/или основных зависимостей, которые наиболее предпочтительны для реализации
- [ ] Отсутствие закоммиченного `.lock` файла зависимостей, если он поддерживается
- [ ] Наличие CI силами GitHub Actions, который запускает тестирование приложения
- [ ] `Dockerfile` и `docker-compose.yml` (+ `.dockerignore`) файлы для быстрого старта шаблона приложения (с указанием в файле `README.md` как минимально с этим делом взаимодействовать)
- [ ] `Makefile` с основными целями, которые могут потребоваться для взаимодействия с приложением (все цели должны достигаться силами докера, естественно)
- [ ] Бэйджики в `README.md` по примеру репозиториев, указанных ниже
- [ ] Переформатированный файл `README.md` по примеру репозиториев, указанных ниже

Примеры репозиториев, в которые есть смысл "поглядывать":

- https://github.com/avtocod/golang-developer-test-task
- https://github.com/avtocod/php-developer-test-task

Результат выполнения оформить в виде отдельного PR, меня назначить ревьювером, по завершению работы ссылку на PR отправить почтовым голубем (экспресс доставки).

**Comment by own3dh4rd** [comment]
В тестовом задании докеризация опциональна и стек технологий максимально произвольный настолько, что не вижу смысла все это делать.

А шаблонизировать для быстрого старта не очень хочется, хочу посмотреть как с этим справится кандидат.

**Comment by tarampampam** [comment]
Этот issue является не вопросом или предложением, а задачей, имеющей свои причины и основания

**Comment by own3dh4rd** [comment]
В любом случае сначала это обсуждают.
Dockerfile и docker-compose получаются настолько простыми, что, вероятно, не имеет смысла это добавлять. Makefile так вообще мега опциольная штуковина.
Придется усложнять тестовое задание, добавляя докеризацию в пункт требований, что я поддерживаю. Но камон, разработчик, который не сможет создать Докерфайл и docker-compose?
Все равно считаю, что нет смысла давать что-то готовое, хочу видеть как получится реализовать.

**Comment by own3dh4rd** [comment]
#3
